//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatawaTranslater {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransTable() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KatawaTranslater.TransTable", typeof(TransTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 $ written_note(,笔记
        ///NONE,自白
        ///shi,静音
        ///hi,久夫
        ///ha,华子
        ///emi,笑美
        ///mi,米莎
        ///li,莉莉
        ///rin,琳
        ///aki,晃
        ///ke,健二
        ///yu,优子
        ///nk,护士
        ///mu,武藤
        ///n,自言 的本地化字符串。
        /// </summary>
        public static string FS {
            get {
                return ResourceManager.GetString("FS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hisao,久夫
        ///Nakai,中井
        ///Emi,笑美
        ///Ibarazaki,茨崎
        ///Hanako,华子
        ///Ikezawa,池泽
        ///Lilly,莉莉
        ///Satou,砂藤
        ///Rin,琳
        ///Tezuka,手塚
        ///Shizune,静音
        ///Hakamichi,羽加道
        ///Shiina,椎名
        ///Misha,米莎
        ///Mikado,御门
        ///Kenji,健二
        ///Seto,濑藤
        ///Nurse,护士
        ///Akio,昭夫
        ///Mutou,武藤
        ///Yuuko,优子
        ///Shirikawa,白川
        ///Iwanako,岩鱼子
        ///Shicchan,小静
        ///Hicchan,小久
        ///Meiko,芽衣子
        ///Jigoro,治五郎
        ///Hideaki,秀明
        ///Akira,晃
        ///Saionji,西园寺
        ///Sae,纱枝
        ///Nomiya,野宫
        ///Yamaku School,山久高校
        ///Yamaku,山久
        ///Shiraki,白木
        ///Miki,美贵
        ///Aoi,葵
        ///Keiko,惠子
        ///my my,嘛～嘛～ 的本地化字符串。
        /// </summary>
        public static string TT {
            get {
                return ResourceManager.GetString("TT", resourceCulture);
            }
        }
    }
}
